export const HomeActionTypes = {
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  GET_WORD_CATEGORIES: 'GET_WORD_CATEGORIES',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SIGN_IN_USER: 'SIGN_UP_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  SET_USER_POINTS: 'SET_USER_POINTS',
};
